version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    environment:
      - JEKYLL_ENV=development
    command: bash -c "bundle install && jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:cached
      - ./vendor/bundle:/usr/local/bundle:cached
